server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE:dev}

  # FILE CONFIG
    servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 10MB

  # DATASOURCE CONFIG
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA CONFIG
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect