name: Parse Database Configuration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  JPA_DDL: ${{ secrets.JPA_DDL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
  JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
  ORIGINS: ${{ secrets.ORIGINS }}
  REDIRECT_URL: ${{ secrets.REDIRECT_URL }}


jobs:
  parse-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Delete existing database configuration
        run: |
          sed -i '/spring\.datasource\.url:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.datasource\.username:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.datasource\.password:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.jpa\.hibernate\.ddl-auto:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.google\.client-id:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.google\.client-secret:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.github\.client-id:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.github\.client-secret:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.facebook\.client-id:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.facebook\.client-secret:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.twitter\.client-id:/d' src/main/resources/application-prod.properties
          sed -i '/spring\.security\.oauth2\.client\.registration\.twitter\.client-secret:/d' src/main/resources/application-prod.properties
          sed -i '/app\.auth\.tokenSecret:/d' src/main/resources/application-prod.properties
          sed -i '/app\.auth\.tokenExpirationMsec:/d' src/main/resources/application-prod.properties
          sed -i '/app\.cors\.allowedOrigins:/d' src/main/resources/application-prod.properties
          sed -i '/app\oauth2\.authorizedRedirectUris:/d' src/main/resources/application-prod.properties

      - name: Replace properties in yml
        run: |
          echo "spring.datasource.url=$DB_URL" >> src/main/resources/application-prod.properties
          echo "spring.datasource.username=$DB_USERNAME" >> src/main/resources/application-prod.properties
          echo "spring.datasource.password=$DB_PASSWORD" >> src/main/resources/application-prod.properties
          echo "spring.jpa.hibernate.ddl-auto=$JPA_DDL" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.google.client-id=$GOOGLE_CLIENT_ID" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.google.client-secret=$GOOGLE_CLIENT_SECRET" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.github.client-id=$GH_CLIENT_ID" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.github.client-secret=$GH_CLIENT_SECRET" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.facebook.client-id=$FACEBOOK_CLIENT_ID" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.facebook.client-secret=$FACEBOOK_CLIENT_SECRET" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.twitter.client-id=$TWITTER_CLIENT_ID" >> src/main/resources/application-prod.properties
          echo "spring.security.oauth2.client.registration.twitter.client-secret=$TWITTER_CLIENT_SECRET" >> src/main/resources/application-prod.properties
          echo "app.auth.tokenSecret=$JWT_TOKEN_SECRET" >> src/main/resources/application-prod.properties
          echo "app.auth.tokenExpirationMsec=$JWT_EXPIRATION_TIME" >> src/main/resources/application-prod.properties
          echo "app.cors.allowedOrigins=$ORIGINS" >> src/main/resources/application-prod.properties
          echo "app.oauth2.authorizedRedirectUris=$REDIRECT_URL" >> src/main/resources/application-prod.properties
          

      # Commit and push all changed files.
      - name: GitHub Commit & Push
#        # Only run on main branch push (e.g. after pull request merge).
#        if: github.event_name == 'push'
        run: |
          git config --global user.name "whalewalker"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "Update production configuration"
          git push

